{% set name = "crbeam" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/okolo/mcray/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 6af2125e82b9aa39a4684b147e5959ad3dc63fe1cdd02d9a7e9b91b23ce5d9f9
build:
  skip: True  # [win or osx]
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
  host:
    - gsl
    - libblas
    - libgomp      # [linux]
    - libboost-devel
test:
  commands:
    - crbeam --help

about:
  home: https://github.com/okolo/mcray
  summary: 'program to simulate propagation of ultra-high energy cosmic rays'
  description: |
    Monte Carlo simulation of ultra-high energy cosmic rays and electromagnetic cascade propagation
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/okolo/mcray/tree/main/src/app/crbeam
  dev_url: https://github.com/okolo/mcray

extra:
  recipe-maintainers:
    - okolo
